apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-evaluation-carts-api
spec:
  template:
    spec:
      containers:
        - name: carts-api
          image: developer-evaluation-carts-api@sha256:__CARTS_API_IMAGE_DIGEST__
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi