apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml

namespace: developer-evaluation-production

replicas:
  - name: developer-evaluation-sales-api
    count: 2
  - name: developer-evaluation-products-api
    count: 2
  - name: developer-evaluation-carts-api
    count: 2
  - name: developer-evaluation-users-api
    count: 2
  - name: developer-evaluation-auth-api
    count: 2

labels:
  - includeSelectors: true
    pairs:
      environment: production

patches:
  - path: namespace.patch.yaml
    target:
      kind: Namespace
      name: developer-evaluation
  - path: configmap-sales.patch.yaml
    target:
      kind: ConfigMap
      name: developer-evaluation-sales-api-config
  - path: configmap-products.patch.yaml
    target:
      kind: ConfigMap
      name: developer-evaluation-products-api-config
  - path: configmap-carts.patch.yaml
    target:
      kind: ConfigMap
      name: developer-evaluation-carts-api-config
  - path: configmap-users.patch.yaml
    target:
      kind: ConfigMap
      name: developer-evaluation-users-api-config
  - path: configmap-auth.patch.yaml
    target:
      kind: ConfigMap
      name: developer-evaluation-auth-api-config
  - path: deployment-sales.patch.yaml
    target:
      kind: Deployment
      name: developer-evaluation-sales-api
  - path: deployment-products.patch.yaml
    target:
      kind: Deployment
      name: developer-evaluation-products-api
  - path: deployment-carts.patch.yaml
    target:
      kind: Deployment
      name: developer-evaluation-carts-api
  - path: deployment-users.patch.yaml
    target:
      kind: Deployment
      name: developer-evaluation-users-api
  - path: deployment-auth.patch.yaml
    target:
      kind: Deployment
      name: developer-evaluation-auth-api