apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-sales-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Development
  Observabilidade__SeqUrl: http://seq:5341
  MongoDb__Database: developer_evaluation_sales
  RabbitMq__QueueName: developer-evaluation.sales.webapi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-products-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Development
  Observabilidade__SeqUrl: http://seq:5341
  MongoDb__Database: developer_evaluation_products
  RabbitMq__QueueName: developer-evaluation.products.webapi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-carts-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Development
  Observabilidade__SeqUrl: http://seq:5341
  MongoDb__Database: developer_evaluation_carts
  RabbitMq__QueueName: developer-evaluation.carts.webapi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-users-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Development
  Observabilidade__SeqUrl: http://seq:5341
  MongoDb__Database: developer_evaluation_users
  RabbitMq__QueueName: developer-evaluation.users.webapi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-auth-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Development
  Observabilidade__SeqUrl: http://seq:5341
  MongoDb__Database: developer_evaluation_auth
