apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-shared-secrets
  namespace: developer-evaluation
type: Opaque
stringData:
  RabbitMq__ConnectionString: amqp://guest:guest@rabbitmq:5672
  ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=developer_evaluation;Username=postgres;Password=postgres
  ConnectionStrings__MongoDb: mongodb://mongodb:27017/developer_evaluation