apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-shared-secrets
  namespace: developer-evaluation-production
type: Opaque
stringData:
  RabbitMq__ConnectionString: amqp://__RABBITMQ_USERNAME__:__RABBITMQ_PASSWORD__@__RABBITMQ_HOST__:__RABBITMQ_PORT__
  ConnectionStrings__MongoDb: mongodb://__MONGODB_HOST__:__MONGODB_PORT__
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-sales-db-secret
  namespace: developer-evaluation-production
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=__POSTGRES_HOST__;Port=__POSTGRES_PORT__;Database=developer_evaluation_sales;Username=__POSTGRES_USERNAME__;Password=__POSTGRES_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-products-db-secret
  namespace: developer-evaluation-production
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=__POSTGRES_HOST__;Port=__POSTGRES_PORT__;Database=developer_evaluation_products;Username=__POSTGRES_USERNAME__;Password=__POSTGRES_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-carts-db-secret
  namespace: developer-evaluation-production
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=__POSTGRES_HOST__;Port=__POSTGRES_PORT__;Database=developer_evaluation_carts;Username=__POSTGRES_USERNAME__;Password=__POSTGRES_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-users-db-secret
  namespace: developer-evaluation-production
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=__POSTGRES_HOST__;Port=__POSTGRES_PORT__;Database=developer_evaluation_users;Username=__POSTGRES_USERNAME__;Password=__POSTGRES_PASSWORD__
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-auth-db-secret
  namespace: developer-evaluation-production
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=__POSTGRES_HOST__;Port=__POSTGRES_PORT__;Database=developer_evaluation_auth;Username=__POSTGRES_USERNAME__;Password=__POSTGRES_PASSWORD__