apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-shared-secrets
  namespace: developer-evaluation
type: Opaque
stringData:
  RabbitMq__ConnectionString: amqp://guest:guest@rabbitmq:5672
  ConnectionStrings__MongoDb: mongodb://mongodb:27017
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-sales-db-secret
  namespace: developer-evaluation
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=developer_evaluation_sales;Username=postgres;Password=postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-products-db-secret
  namespace: developer-evaluation
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=developer_evaluation_products;Username=postgres;Password=postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-carts-db-secret
  namespace: developer-evaluation
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=developer_evaluation_carts;Username=postgres;Password=postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-users-db-secret
  namespace: developer-evaluation
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=developer_evaluation_users;Username=postgres;Password=postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-evaluation-auth-db-secret
  namespace: developer-evaluation
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=developer_evaluation_auth;Username=postgres;Password=postgres