apiVersion: v1
kind: Service
metadata:
  name: developer-evaluation-api
  namespace: developer-evaluation
spec:
  selector:
    app: developer-evaluation-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP