apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-sales-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Production
  Observabilidade__SeqUrl: http://__SEQ_HOST__:__SEQ_PORT__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-products-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Production
  Observabilidade__SeqUrl: http://__SEQ_HOST__:__SEQ_PORT__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-carts-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Production
  Observabilidade__SeqUrl: http://__SEQ_HOST__:__SEQ_PORT__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-users-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Production
  Observabilidade__SeqUrl: http://__SEQ_HOST__:__SEQ_PORT__
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: developer-evaluation-auth-api-config
  namespace: developer-evaluation
data:
  ASPNETCORE_ENVIRONMENT: Production
  Observabilidade__SeqUrl: http://__SEQ_HOST__:__SEQ_PORT__