apiVersion: v1
kind: Service
metadata:
  name: developer-evaluation-sales-api
  namespace: developer-evaluation
spec:
  selector:
    app: developer-evaluation-sales-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: developer-evaluation-products-api
  namespace: developer-evaluation
spec:
  selector:
    app: developer-evaluation-products-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: developer-evaluation-carts-api
  namespace: developer-evaluation
spec:
  selector:
    app: developer-evaluation-carts-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: developer-evaluation-users-api
  namespace: developer-evaluation
spec:
  selector:
    app: developer-evaluation-users-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: developer-evaluation-auth-api
  namespace: developer-evaluation
spec:
  selector:
    app: developer-evaluation-auth-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP